### ISSUE TITLE
SGX-LKL documentation (paper?)

### ISSUE THREAD

**Issue by zavalyshyn** [lsds/sgx-lkl#11]
Hi,

I've tried sgx-lkl (jvm example) and it seems to run properly. There are few things that I'd like to clarify though. 

First of all, is there any documentation available for this software? The Wiki section leads to the repo front page. There is no link to any documentation in the README file. Was there any paper published on sgx-lkl?

I mainly look for documentation to clarify my other concerns. 

- For instance, how I can verify that the HelloWorld example is indeed running in the SGX enclave? 
- What are the security guarantees SGX-LKL provides? 
- How can I prove those?

Finally, seems like the developers of SGX-LKL come from the same group that worked on SCONE, which I also tested previously. What system is more actively developed and should be thus used? 

Thanks

**Comment by prp** [comment]
Hi,

Since SGX-LKL is an ongoing research project, we unfortunately don't have documentation beyond the README file and the source code. We are currently in the process of writing a research paper about it.

Regarding your questions, all of the source code of SGX-LKL is available, and you can verify that the code indeed is launched inside of the enclave. In general, the security guarantees are similar to what Graphene-SGX or SCONE provide. In ongoing work, we aim to give stronger guarantees regarding possible data leakage across the interface to the host OS.

SGX-LKL is an early fork of SCONE, done at the time before the SCONE paper was published, and has since evolved independently. SCONE is a separate commercial offering.

**Comment by zavalyshyn** [comment]
Great. Thanks for your explanation. I will stick to SCONE then.

**Comment by kanakraju73** [comment]
Any update on this?
