### ISSUE TITLE
Large number of ethread idle calls?

### ISSUE THREAD

**Issue by prp** [lsds/sgx-lkl#191]
We observe a large number of ethread idle host calls when running an application:
```
:~/devel/sgx-lkl-oe-lsds.git/tests/languages/java$ make run-hw 2>&1 | grep "sgxlkl_host_idle_ethread: enter" | wc -l
99028
```
This may be due to a bug in the integration of the virtio layer with the lthread scheduler.

This may be related to https://github.com/lsds/sgx-lkl/issues/190.

**Comment by davidchisnall** [comment]
How many ethreads are running? Until we fix #190 and can move to an entirely tickles implementation, ethreads with no work to do in the scheduler will keep exiting, hitting a small timeout, returning, finding nothing to do, and repeating the process. This is far from ideal, but shouldn’t impact throughout of the ethreads with real work to do.

**Comment by prp** [comment]
@davidchisnall This was with 8 ethreads. Here is a table:

num of ethreads | num of idle ethread calls
--- | ---
8 | 99,028
4 | 69,193
2 | 38,544
1 | 0

Something isn't right here. Shouldn't this increase somewhat linearly? Also, note that this is the JVM initialising, so I would presume that there should be a fair amount of potential for concurrency.

**Comment by davidchisnall** [comment]
As I recall,  most of OpenJDK init is single threaded. The JVM itself will create a pool of threads, but these will be mostly idle until it’s either in a GC phase, doing a lot of async I/O, or running application threads. If you’re doing printf, Java will load and initialise a load of locale-related things. These involve a load of class loader things, which are all done with a big lock held.

**Comment by davidchisnall** [comment]
Also, as the number of ethreads approaches the number of VCPUs, they will start to compete with host threads for CPU time, so I’d expect the number of ocalls to go down a bit, which does seem to be what’s happening. One ethreads is running the only runnable lthread (since there’s some I/O going on, there are probably 2 runnable lthreads some of the time), the others are checking, having nothing to do, and ocalling. If other pthreads and kernel threads are runnable on the host then the timeouts in the ocalls will be extended, so we’ll see fewer ocalls per ethreads with higher ethread counts.

Once we’ve fixed #190, the timeout should be replaced with the next timer value and so we should see most ethreads just waiting for I/O on a workload like this, with little difference in CPU usage between 2 and 8 ethreads.

**Comment by davidchisnall** [comment]
It might be worth trying to compile LKL as a tickless kernel. Currently, LKL registers for a periodic timer callback and often doesn’t the do anything in the wake up. In tickless mode, the kernel scheduler will only ask LKL for a timer interrupt when it has some work to do. This will probably break things until #190 is fixed, but after that we should be able to completely suspend all ethreads until we see an event on one of the devices.

**Comment by SeanTAllen** [comment]
This now has a higher priority than #190, that seems wrong. @prp @davidchisnall this is dependent on #190, yes?

**Comment by prp** [comment]
This issue is about performance. #190 may be contributing to it, but I doubt that it is a major factor. Since we don't have evidence about how severe a performance issue this is, I would propose to make this P2.

**Comment by SeanTAllen** [comment]
I've removed p1 for now, added needs-triage label and added the the Issue Triage project as a Proposed p2.

**Comment by davidchisnall** [comment]
I think there are two causes of this.  One is the virtio polling the other is the fact that we don't build Linux in tickless mode.  As a result, it asks for a regular timer tick, even if it has no work to do.  This means that, when idle, we will always wake up every few ms to enter the enclave, invoke the LKL idle routine, discover we have no work to do, and exit again.

**Comment by bodzhang** [comment]
Unexpected large number of ethread idle host call might be another indication of synchronization bugs, which can have security implication. I think we need to treat this one as P1.

**Comment by prp** [comment]
The measurements above are several months old, so it is not clear if this is still a current issue.

**Comment by davidchisnall** [comment]
@bodzhang, I'm not sure I understand your logic there.  ethread idle calls happen when there are no runnable lthreads.  We have a lot of them (we believe) because we hit the (low) timeout and spuriously return ealry, only to check the result in the end and then do the ecall again.

This is bad for production because it means we consume a lot of CPU time when idle.  It is unlikely to have any security impact.

**Comment by bodzhang** [comment]
@davidchisnall, [this post](https://github.com/lsds/sgx-lkl/pull/758#issuecomment-672338616) provided a speculation - if the potential sync issue pointed out indeed causes wake up event lose and sleeping lthreads not being waking up, it can explain idle ethreads situation. Synchronization bug can have security implication.

**Comment by prp** [comment]
This code has received more scrutiny, and I don't think that there is a problem beyond what is documented in https://github.com/lsds/sgx-lkl/issues/190. I am closing this issue.
