### ISSUE TITLE
How to modify the JRE so it can run in SGX-LKL enclave?

### ISSUE THREAD

**Issue by avigail-oron** [lsds/sgx-lkl#28]
The jre from https://lsds.doc.ic.ac.uk/files/sgxlkl_openjdk_jre_alpine_8.121.13-r0.tar.gz that is used in the jvm sample apps does not contain a module I need (nss).
Trying to create my own image with a JRE from existing alpine packages fails, even though it's working perfectly in docker alpine-based container.
What changes need to be made to adjust the JRE to run in SGX-LKL? 
(One obvious change is the use of LD_LIBRARY_PATH instead of relying on RPATH)

**Comment by cpriebe** [comment]
There are two issues with the pre-packaged Alpine OpenJDK:
1. It uses 'execve' under certain circumstances which SGX-LKL currently does not support.
2. It requires file-backed mmap support which (this version of ) SGX-LKL currently does not support.

You can get around the first issue by making sure the LD_LIBRARY_PATH starts with a specific prefix which the JVM checks against when deciding whether to rerun via execve. The second issue requires changes to SGX-LKL. Memory-mapping files is obviously not the best idea in a memory-restricted environment such as Intel SGX enclaves but it's possible to disable most of the memory-mapped I/O via runtime parameters. The remaining mappings still need to be supported by SGX-LKL.

Anyway, we actually do have a fix for both issues internally that allows SGX-LKL to run with the official Alpine OpenJDK8 JRE. It needs a bit of cleaning up but I will try to do that and push the change in the next few days.

**Comment by avigail-oron** [comment]
Thank you!

**Comment by cpriebe** [comment]
With the most recent commit, SGX-LKL now supports the Alpine-packaged OpenJDK8 JRE. The HelloWorld example and the `sgx-lkl-java` wrapper have been updated accordingly.

Two important notes on this:
1) The LD_LIBRARY_PATH has to be set and has to start with `/usr/lib/jvm/java-1.8-openjdk/jre/lib/amd64/server:/usr/lib/jvm/java-1.8-openjdk/jre/lib/amd64:/usr/lib/jvm/java-1.8-openjdk/jre/../lib/amd64` in order to prevent the JVM from re-executing `java` via `execve`.
2) File-mapped mmap has to be specifically enabled for SGX-LKL. This is necessary because the JVM will mmap a small portion of the runtime library `rt.jar`.

Both of these requirements are incorporated into the the `sgx-lkl-java` tool.
