### ISSUE TITLE
Investigate pipeline-local run gap for java read file test

### ISSUE THREAD

**Issue by hukoyu** [lsds/sgx-lkl#283]
@davidchisnall says this test passes locally everytime and only fails on pipeline randomly. 
Investigate if there is gap between pipeline and local run that causing these flaky failures or this is a sgx-lkl product bug.

cc @hukoyu

**Comment by SeanTAllen** [comment]
I set up a new dev machine the other day.

On my previous machine, I was unable to recreate any problems with JVM tests. However, on the new box, all of them have problems with being very slow. However, the problem is intermittent. I can do many runs in a row of SW mode without issue before hitting on that hangs for a long period of time. It looks like it is deadlocked but when I am patient enough, it sometimes continues. Other times, it has hung long enough that I give up and cancel it.

In [enclave_init.c](https://github.com/lsds/sgx-lkl/blob/oe_port/src/enclave/enclave_init.c#L209) hardcoding libc.user_tls_enabled to 0 makes the problem much less severe.

Locally with that change, all the JVM tests were snappy, however even with that change, I did get a JVM test timing out in CI. 

I'm not sure what the cause of this is my I wanted to report the symptom.

Note this problem applies to all JVM tests. Including the Hello World that was turned off for CI because it would also time out after 5 minutes sometimes. 

It should be noted that HW mode is much slower for me than SW mode without the above tls_enabled change. However in CI, both SW and HW sometimes time out and without the change, SW mode still feels sluggish. 

The sluggish nature of the run is not confined to a particular point in time during the applications lifecycle. My first thought when looking at it was that due to the low amount of memory allocated to various JVM bits in sgx-lkl-java, that it was GCing. Running with -verbose:gc as one of the JVM options did not show an excessive amount of GC, although I did see 1 `GC (Allocation Failure)`.

For me locally, doing, seems to correct the problem with HW mode without any code changes:

`  cd tools/kmod-set-fsgsbase; make set-cr4-fsgsbase`

From the docs:

```
Support for Thread-Local Storage (TLS) in hardware mode

On x86-64 platforms thread-local storage for applications and their initially
available dependencies is expected to be accessible via fixed offsets from the
current value of the FS segment base. Whenever a switch from one thread to
another occurs, the FS segment base has to be changed accordingly. Typically
this is done by the privileged kernel. However, with SGX the FS segment base is
explicitly set when entering the enclave (OFSBASE field of the TCS page) and
reset when leaving the enclave. SGX-LKL schedules application threads within
the enclaves without leaving the enclave. It therefore needs to be able to set
the FS segment base on context switches. This can be done with the WRFSBASE
instruction that allows to set the FS segment base at any privilege level.
However, this is only possible if the control register bit CR4.FSGSBASE is set
to 1. On current Linux kernels this bit is not set as the kernel is not able to
handle FS segment base changes by userspace applications. Note that changes to
the segment from within an enclave are transparent to the kernel.

In order to allow SGX-LKL to set the segment base from within the enclave, the
CR4.FSGSBASE bit has to be set to 1. SGX-LKL provides a kernel module to do
this. In order to build the module and set the CR4.FSGSBASE to 1 run the
following:

  cd tools/kmod-set-fsgsbase; make set-cr4-fsgsbase

In order to set it back to 0, run:

  cd tools/kmod-set-fsgsbase; make unset-cr4-fsgsbase

WARNING: While using WRFSBASE within the enclave should have no impact on the
host OS, allowing other userspace applications to use it can impact the
stability of those applications and potentially the kernel itself. Enabling
FSGSBASE should be done with care.
```

However, fsgsbase has no impact on SW mode which still hangs for a very long time on occasion.

My suspicion is that the SW mode hang is a different issue than the slowness with HW mode.

**Comment by SeanTAllen** [comment]
This issue impacts all the java tests in HW mode.

**Comment by jxyang** [comment]
Suggest a modified pipeline that runs Java tests only, and post a log here when the failure happens.

**Comment by hukoyu** [comment]
This issue doesn't repro with latest code. Looks like fixed.
