### ISSUE TITLE
Allow applications to install SIGFPE signal handlers

### ISSUE THREAD

**Issue by letmaik** [lsds/sgx-lkl#36]
Some applications install them and currently SGX-LKL would exit instead of calling the installed signal handler.

**Comment by letmaik** [comment]
I stumbled over this again, any chance it could be implemented?

**Comment by cpriebe** [comment]
Hi Maik,

apologies for the delay! Definitely. We have been busy working on a number of other things, in particular remote attestation, Wireguard support, and x86 hardware acceleration for disk encryption and integrity protection. All of that should be in a decent state now and I hope I can push those changes soon.

Once that's done, improving the signal handling and allowing custom signal handlers for other signals than SIGSEGV is one of the next things I want to look at.

**Comment by cpriebe** [comment]
I actually just had a look at this and added some rudimentary SIGFPE signal handling support. Maybe you can give it a try and let me know if this is enough for your use case? Right now, there is no support yet for advanced things like signal masking or alternative signal stacks though. If the change in this commit isn't enough it would be good to have some way of reproducing the issue to see what's missing.

Potentially fixed in 191a922 / https://github.com/lsds/sgx-lkl-musl/commit/5433eb2f0d018434429ff5a63cb291130808c745.

**Comment by letmaik** [comment]
Thanks! It's working!
