### ISSUE TITLE
lkl_deliver_irq ignores errors

### ISSUE THREAD

**Issue by letmaik** [lsds/sgx-lkl#371]
Return code of `lkl_trigger_irq()` is not checked.

**Comment by SeanTAllen** [comment]
in my limited testing, the lkl_trigger_irq for console returns a non-zero on almost every shutdown in sw-mode.

**Comment by SeanTAllen** [comment]
We took a quick a look at this during triaging.

From

```
int lkl_cpu_try_run_irq(int irq)
{
	int ret;

	ret = __cpu_try_get_lock(1);
	if (!ret) {
		set_irq_pending(irq);
		cpu.irqs_pending = true;
	}
	__cpu_try_get_unlock(ret, 1);

	return ret;
}
```

It looks like this could cause bad things to happen including losing virtio related irqs. We should be retrying if we get a failure. We should be checking the return values and queuing up to try again.

Talk to @davidchisnall if you need more information.

**Comment by davidchisnall** [comment]
May be related to #559

**Comment by prp** [comment]
I think that there are two cases when `lkl_trigger_irq()` fails:
1. something else has the CPU lock -- in that case, it will mark the IRQ as pending, and it will be handled when the CPU lock is released;
2. LKL is shutting down -- in that case, the IRQ may never be handled.

It seems to me that the right thing should happen for (1) without any action in the virtio layer.

For (2), we need to ensure that we are shutting down the virtio layer before the CPU has been halted.

#559 seems different to me, as it results in a failure early on during the initialisation sequence.

**Comment by davidchisnall** [comment]
The try get lock call is confusing. This function returns 1 on success, <1 on failure. If the return value is less than 0, we shutdown is happening and we will not set the pending flag. If we fail to acquire the cpu lock but are not shutting down, the return is 0 and we will set the pending flag, hopefully then the right thing happens. If we do acquire the cpu lock, nothing happens, which confuses me. I would expect this to call run_irqs if it does successfully acquire the lock.

It looks as if an IRQ delivered when nothing is running in LKL will be lost.

**Comment by prp** [comment]
I don't understand. When `lkl_cpu_try_run_irq()` returns 1, it will execute the IRQs here: https://github.com/lsds/lkl/blob/73637e73a994005322e0d6b8909b25850d9caa1c/arch/lkl/kernel/irq.c#L98

**Comment by davidchisnall** [comment]
Ah, sorry, I was only looking at the code in cpu.c.  That makes sense  - in that case I think it's fine to ignore errors for `lkl_trigger_irq`: as you said, this will only ever happen during shutdown and there's no correct handling for trying to deliver an IRQ to a kernel that's shutting down.  

Looking at that code; however, I am concerned that we are holding a ticket lock while calling `lkl_trigger_irq`.  This function can yield and yielding with a ticket lock held is dangerous because it can cause deadlock.

**Comment by davidchisnall** [comment]
The ticket lock issue is probably benign because it looks as if only one thread can ever attempt to acquire that lock, which then makes me wonder why we have the lock at all.  I think the goal of the lock is make the updates to the IRQ pending bit atomic.  Unfortunately, this seems to be assuming that this bit is updated only when the lock is held: when LKL clears the bit, that lock is not held and so we can potentially lose some wakeups.

**Comment by davidchisnall** [comment]
#762 cleans up this code.  I propose closing this issue because there is nothing useful that we can do with this return value.

**Comment by SeanTAllen** [comment]
Closing per @davidchisnall comment above. This can be reopened if there is disagreement.
