### ISSUE TITLE
console_enqueue() has incorrect error handling

### ISSUE THREAD

**Issue by letmaik** [lsds/sgx-lkl#374]
https://github.com/lsds/sgx-lkl/blob/6016fbc9eabda2799ac914c8278e37d2e2f385b2/src/host_interface/virtio_console.c#L172-L199

- No status code is returned.
- `virtio_req_complete()` is called with status code that may be a negative error code, but the function accepts unsigned integers only which is the length of data processed. Should `virtio_req_complete()` be called with length 0 in case of errors? Or should a `readv` failure always lead to a fatal exit?

**Comment by SeanTAllen** [comment]
Based on reading docs in `virtio_dev_ops` struct...

```c
	/**
	 * enqueue - queues the request for processing
	 *
	 * Note that the curret implementation assumes that the requests are
	 * processed synchronous and, as such, @virtio_req_complete must be
	 * called by from this function.
	 *
	 * @dev - virtio device
	 * @q	- queue index
	 *
	 * @returns a negative value if the request has not been queued for
	 * processing in which case the virtio device is resposible for
	 * restaring the queue processing by calling @virtio_process_queue at a
	 * later time; 0 or a positive value means that the request has been
	 * queued for processing
	 */
```

We want to return a negative value (nothing is indicated so for now, I will go with -1 otherwise 0 for success).

The warning in the code seems pointless to me. I'm not sure of the utility.

I propose:

return values:

* -1 as return value indicating an error
* 0 for sucess

Also:

* writev should also be verifying that EINTR didn't happen same as readv
* change `ret` to be the correct `ssize_t` as that is the return type for readv and writev
---

Two things I am unclear on:

```
	 * Note that the curret implementation assumes that the requests are
	 * processed synchronous and, as such, @virtio_req_complete must be
	 * called by from this function.
```

Does the "must" there include when a failure has occurred?

```
	 * @returns a negative value if the request has not been queued for
	 * processing in which case the virtio device is resposible for
	 * restaring the queue processing by calling @virtio_process_queue at a
	 * later time; 0 or a positive value means that the request has been
	 * queued for processing
```

virtio_process_queue, is that something we are currently doing anywhere? If not then I assume it needs to be added. I don't know at the moment and need to look into what is happening currently.

@prp @davidchisnall do you have any input?

**Comment by davidchisnall** [comment]
Note that this is the bootstrap console, before we've really attaching the proper virtio console.  I don't think we care if we lose some output there.

**Comment by SeanTAllen** [comment]
@davidchisnall it is? where is the "proper" one brought up?

**Comment by davidchisnall** [comment]
Sorry, I was misreading the code and talking nonsense.  Ignore me.

**Comment by SeanTAllen** [comment]
`virtio_process_queue` is called in a loop from `console_task` so I think we are good on that front.

**Comment by SeanTAllen** [comment]
Elsewhere in the codebase we call `virtio_req_complete` on errors with a 0 for the byte-length. See `blk_enqueue` for example. So I believe it should always be called and with a 0, if we got an error.

And we are returning -1 for errors elsewhere and 0 for success (see for example `net_enqueue`)

**Comment by prp** [comment]
Yes, @SeanTAllen, I think that, after a read or write error, `console_enqueue()` should not call `virtio_req_complete()` and return -1. My suspicion is that calling `virtio_req_complete()` with `len == 0` is equivalent to not calling it at all.

**Comment by SeanTAllen** [comment]
@prp given we call it with 0 elsewhere for error, I'd feel more comfortable doing the same here. Are you ok with that?
