### ISSUE TITLE
Not clear if sample fails or passes

### ISSUE THREAD

**Issue by lshacham** [lsds/sgx-lkl#5]
**Summary**: 
Running the jvm sample, I cannot tell if run passed or not. Could you please update either printfs or README.md to clarify? 

**Details**: 

I run: 

<my path to sgx-lkl>sgx-lkl/apps/jvm/helloworld-java$ sudo ../../../tools/sgx-lkl-java ./sgxlkl-java-fs.img HelloWorld

And get: 

[    0.000000] Linux version 4.10.0+ (my user name) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4) ) #1 Tue Apr 17 08:42:47 EET 2018
[    0.000000] bootmem address range: <***> - <***>
[    0.000000] Built 1 zonelists in Zone order, mobility grouping off.  Total pages: 3029
[    0.000000] Kernel command line:  virtio_mmio.device=292@0x1000000:1 virtio_mmio.device=268@0x2000000:2
[    0.000000] PID hash table entries: 64 (order: -3, 512 bytes)
[    0.000000] Dentry cache hash table entries: 2048 (order: 2, 16384 bytes)
[    0.000000] Inode-cache hash table entries: 1024 (order: 1, 8192 bytes)
[    0.000000] Memory available: 11988k/0k RAM
[    0.000000] SLUB: HWalign=32, Order=0-3, MinObjects=0, CPUs=1, Nodes=1
[    0.000000] NR_IRQS:4096
[    0.000000] lkl: irqs initialized
[    0.000000] clocksource: lkl: mask: 0xffffffffffffffff max_cycles: 0x1cd42e4dffb, max_idle_ns: 881590591483 ns
[    0.004228] lkl: time and timers initialized (irq3)
[    0.004289] pid_max: default: 4096 minimum: 301
[    0.004350] Mount-cache hash table entries: 512 (order: 0, 4096 bytes)
[    0.004353] Mountpoint-cache hash table entries: 512 (order: 0, 4096 bytes)
[    0.006518] devtmpfs: initialized
[    0.010606] console [lkl_console0] enabled
[    0.010669] clocksource: jiffies: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 19112604462750000 ns
[    0.010734] NET: Registered protocol family 16
[    0.011985] clocksource: Switched to clocksource lkl
[    0.012564] NET: Registered protocol family 2
[    0.012696] TCP established hash table entries: 512 (order: 0, 4096 bytes)
[    0.012701] TCP bind hash table entries: 512 (order: 0, 4096 bytes)
[    0.012706] TCP: Hash tables configured (established 512 bind 512)
[    0.012769] UDP hash table entries: 128 (order: 0, 4096 bytes)
[    0.012774] UDP-Lite hash table entries: 128 (order: 0, 4096 bytes)
[    0.012826] NET: Registered protocol family 1
[    0.012890] virtio-mmio: Registering device virtio-mmio.0 at <***>-<***>, IRQ 1.
[    0.012958] virtio-mmio: Registering device virtio-mmio.1 at <***>-<***>, IRQ 2.
[    0.013407] workingset: timestamp_bits=62 max_order=12 bucket_order=0
[    0.017074] io scheduler noop registered
[    0.017078] io scheduler deadline registered
[    0.017141] io scheduler cfq registered (default)
[    0.017210] virtio-mmio virtio-mmio.0: Failed to enable 64-bit or 32-bit DMA.  Trying to continue, but this might not work.
[    0.017276] virtio-mmio virtio-mmio.1: Failed to enable 64-bit or 32-bit DMA.  Trying to continue, but this might not work.
[    0.043016] mousedev: PS/2 mouse device common for all mice
[    0.043276] NET: Registered protocol family 10
[    0.043622] Segment Routing with IPv6
[    0.043686] sit: IPv6, IPv4 and MPLS over IPv4 tunneling driver
[    0.043982] Warning: unable to open an initial console.
[    0.044046] This architecture does not have kernel memory protection.
[    0.045674] EXT4-fs (vda): mounted filesystem with ordered data mode. Opts: 
[    0.106180] random: fast init done
OpenJDK 64-Bit Server VM warning: Can't detect initial thread stack location - find_vma failed
Hello world!
[    0.247625] reboot: Restarting system

Specifically, the confusing parts are: 
1. virtio-mmio virtio-mmio.0: Failed to enable 64-bit or 32-bit DMA.  Trying to continue, but this might not work. // Did it eventually work? 
2. virtio-mmio virtio-mmio.1: Failed to enable 64-bit or 32-bit DMA.  Trying to continue, but this might not work. // Did it eventually work? 
3. Warning: unable to open an initial console. // Does this mean it fails? 
4. This architecture does not have kernel memory protection. // Does this mean it fails? 
5. warning: Can't detect initial thread stack location - find_vma failed // Does this mean it fails? 
6. Hello world! // Does this mean it succeeds? 
7. reboot: Restarting system // Does this mean it failed?

**Comment by cpriebe** [comment]
Thanks Jiron!

First of all, yes, the example runs successfully.

I agree that receiving all these kernel messages is indeed a bit confusing. `tools/sgx-lkl-java` is a wrapper around `sgx-lkl-run` for which `SGXLKL_VERBOSE` was previously set to 1. I changed this to not print kernel/SGX-LKL debug information by default in https://github.com/lsds/sgx-lkl/commit/ba2cbca9e93e4637ec619c2a44d7985ca0c1484a.

The kernel messages that you mention are warnings related to running the kernel inside an enclave/in userspace, but do not affect SGX-LKL (or the JVM in this case). For example, LKL is implemented as a no-MMU architectural port of Linux. The address space is shared between the kernel and the application, which is why you see a message regarding missing kernel protection. The warnings regarding DMA and the initial console can safely be ignored when running SGX-LKL as well.

With the aforementioned commit, these messages will not be shown without explicitly setting `SGXLKL_VERBOSE=1`.

The JVM warning is caused by the fact that the JVM is trying to read from `/proc/self/maps` which typically contains information about the memory mappings within the application's address space. While we do have in-enclave support for the `/proc` file system, `/proc/self/maps` is currently not populated by SGX-LKL. We might add this in the future. But it's not required for the JVM to work.

I have added a note on this to the README (see https://github.com/lsds/sgx-lkl/commit/9c285a55bf9d2e3200fc6a06ad60ec8ac9652587).

**Comment by lshacham** [comment]
Summary: better but still not clear. 

Details: 

I cleaned and built again:
make clean
make

I then run: 

sudo ../../../tools/sgx-lkl-java ./sgxlkl-java-fs.img HelloWorld

Output: 

write to fd netdev fails: No error information
OpenJDK 64-Bit Server VM warning: Can't detect initial thread stack location - find_vma failed
Hello world!
