### ISSUE TITLE
[Tests] fsync LTP tests should be run

### ISSUE THREAD

**Issue by davidchisnall** [lsds/sgx-lkl#552]
The patches to run the fsync tests are wrong and so #549 has disabled them.  The tests check things that should work and so we should enable them.

**Comment by hukoyu** [comment]
fsync01 enabled with PR https://github.com/lsds/sgx-lkl/pull/601

**Comment by hukoyu** [comment]
fsync02 and fsync03 fixed and enabled with PR https://github.com/lsds/sgx-lkl/pull/602 

fsync04 is not supported since
fsync04 test writes directly to block device. It's not proper to use /dev/vda as it can corrupt. sgx-lkl does not have any other block device inside enclave which we can use. So this test is not supported. It will remain disabled.
