### ISSUE TITLE
Race condition on deletion of detached cloned threads

### ISSUE THREAD

**Issue by vtikoo** [lsds/sgx-lkl#627]
There is a race condition with detached threads created via `clone`, which can cause the parent thread's lthread structures to be free'd >1 times. This happens if the tid in thread_info for the cloned threads has not been restored at the time of `threads_cleanup` in the termination sequence. The [tid](https://github.com/lsds/lkl/blob/86819ac5446e1fa31ca67db68aa165bbf07b90a9/arch/lkl/include/asm/thread_info.h#L23) field in `thread_info` struct is the pointer to the lthread backing the cloned thread. 

The [tid of the child thread is set to its parent](https://github.com/lsds/lkl/blob/86819ac5446e1fa31ca67db68aa165bbf07b90a9/arch/lkl/kernel/syscalls.c#L215-L227) right after `clone` syscall is executed. And is restored when it invokes the exit system call(or does any other syscall?). 

If the parent thread exits before the child cloned threads have restored their tid and invokes the termination sequence, this can cause the main thread's lthread structure to be free'd multiple times causing enclave to abort.

This failure scenario is more probable in the case when the number of spawned cloned threads > number of ethreads available.

Heres a modified version of the `test/basic/clone` which can trigger this failure if run with SGXLKL_ETHREADS < 2.
```C
#include <errno.h>
#include <stdarg.h>
#include <stdio.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include <signal.h>

#define _GNU_SOURCE
#include <sched.h>
#include <unistd.h>
#include <sys/syscall.h>
#include <sys/mman.h>

static char *child_stack;
static char *child_stack_end;
static char child_tls[4069];
static char child_tls1[4069];
static char child_tls2[4069];

static char child_stack1[8192];
static char *child_stack_end1 = child_stack1 + 8192;
static char child_stack2[8192];
static char *child_stack_end2 = child_stack2 + 8192;

int parallelthr(void* arg)
{
	return 0;
}

int main(int argc, char** argv)
{
	unsigned flags = CLONE_VM | CLONE_FS | CLONE_FILES | CLONE_SIGHAND
		| CLONE_THREAD | CLONE_SYSVSEM | CLONE_SETTLS | CLONE_CHILD_SETTID
		| CLONE_PARENT_SETTID | CLONE_CHILD_CLEARTID | CLONE_DETACHED;

	pid_t ptid;

	pid_t ctid_futex1, ctid_futex2;
	pid_t ctid1 = clone(parallelthr, child_stack_end1, flags, (void*)0, &ptid, &child_tls1, NULL);
	pid_t ctid2 = clone(parallelthr, child_stack_end2, flags, (void*)0x1, &ptid, &child_tls2, NULL);
	return 0;
}
```

**Comment by vtikoo** [comment]
cc @jxyang @davidchisnall

**Comment by jxyang** [comment]
Note this is an issue existed before lthread untangling.

**Comment by davidchisnall** [comment]
@vtikoo, I don't see where the tid of the child is set to the parent.

**Comment by vtikoo** [comment]
@davidchisnall the call to `switch_to_host_task` [here ](https://github.com/lsds/lkl/blob/86819ac5446e1fa31ca67db68aa165bbf07b90a9/arch/lkl/kernel/syscalls.c#L223) with the child's `task_struct` and then setting the `tid` [here ](https://github.com/lsds/lkl/blob/86819ac5446e1fa31ca67db68aa165bbf07b90a9/arch/lkl/kernel/threads.c#L201)to the current lthread achieves this.

**Comment by davidchisnall** [comment]
Aha, I see, thanks.  We need that `switch_to_host_task` to make the thread scheduleable, but I hadn't realised that it unconditionally set the tid.  That won't matter *if* the newly spawned thread does any system call, because the next `switch_to_host_task` will then reset the `tid` to the correct lthread, but in your test, I understand correctly, LKL is shutting down before the new lthread issues any system calls and so it retains the parent thread's tid.  The correct solution might be to make the assignment to the `tid` conditional (e.g. assign only if it's 0), but it looks as if that assignment is actually redundant: LKL always assigns the thread when we create a task for a thread.  Alternatively, since the child task is initialised with the correct tid, we can just save and restore it across the `switch_to_host_task` call.  That's probably safer because there might be some subtle behaviour related to `host0` that requires reassigning the tid for a task.
