### ISSUE TITLE
Fix broken samples

### ISSUE THREAD

**Issue by AntonioND** [lsds/sgx-lkl#831]
While working on https://github.com/lsds/sgx-lkl/issues/231 I've found the following issues:

The following samples are broken: ``languages/nodejs`` (Abort), ``languages/openmp`` (The test program hangs).

Also, in ``containers/encrypted``, the Makefile targets ``run-hw-integrity`` and ``run-sw-integrity`` don't seem to work.

Finally, regarding ``languages/java``, it prints a test message and then it hangs. I'm not sure what the expected behaviour is, but I would expect it to print it and exit. It just seems to hang after printing it.

EDIT: Also, the ``ml`` samples don't work with ETHREADS=1.

**Comment by prp** [comment]
* `languages/nodejs` is currently broken because of https://github.com/lsds/sgx-lkl/issues/779. Hopefully this will be fixed soon.
* `languages/openmp` is broken because of https://github.com/lsds/sgx-lkl/issues/535. This is due to a fundamental incompatibility, as documented here: https://github.com/lsds/sgx-lkl/blob/oe_port/docs/Incompatibilities.md#calling-system-calls. A possible workaround would be to move to a different OpenMP runtime that doesn't issue direct system calls.
* `languages/java` has issues because of https://github.com/lsds/sgx-lkl/issues/680.

**Comment by AntonioND** [comment]
The ``languages/java`` sample has been fixed by setting the number of ethreads to 4 in https://github.com/lsds/sgx-lkl/pull/829.
